# Generated by Django 5.0 on 2023-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
