# Generated by Django 5.0 on 2023-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.IntegerField(),
        ),
    ]
