# Generated by Django 5.0 on 2023-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_alter_data_intensity_alter_data_likelihood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(verbose_name='%B, %d %Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
