# Generated by Django 5.0 on 2023-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_alter_data_added_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(verbose_name='%B, %d %Y %H:%M:%S'),
        ),
    ]
