# Generated by Django 5.0 on 2023-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
