# Generated by Django 5.0 on 2023-12-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_alter_data_added_alter_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(max_length=100),
        ),
    ]
